name: Fabric Build

on:
  push:
    paths:
      - 'fabric/**'
  
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'temurin'
    
    - name: Build project
      run: |
        cd ./fabric
        chmod 777 gradlew
        ./gradlew build --dry-run
